#application.yml의 profile설정값에 의해 동적으로 yml파일이 설정된다.
#ex)application-{profile}.properties

############## properties ################
comp:
  name: product
  hp: 02-123-1234
  addr: prodAddr
  
profile:
  name: prod
##########################################

################### 설정 #################
server:
  port: 3000

spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /db  # 콘솔의 경로
  
  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
  
  jpa:
    hibernate:
      ddl-auto: validate # 스키마관리 

logging:
  file: logs/application.log #생성되는 로그파일 위치
  level:
    org:
      thymeleaf: INFO
      springframework.web: INFO
      hibernate.SQL: INFO
      quartz.core: INFO
      h2.server.web: INFO
    com: #패키지별 로깅 설정
      song: INFO